-- ═══════════════════════════════════════════════════════════════
--  incremental_schedules.sql
--
--  Backing tables for the admin console's Schedules tab: a per-year
--  schedule configuration (which structure the school uses and which
--  days its week runs on) plus reusable bell schedules — named sets of
--  ordered time blocks a director can apply to any section.
--
--  Design notes:
--
--    • Schedule entries keep their own concrete start/end times and do
--      NOT reference a bell-schedule block. Templates are an authoring
--      aid: picking one prefills the editor grid, and the row that gets
--      written is a plain `schedules` row. That keeps the student and
--      teacher reads join-free, means editing a template never rewrites
--      or orphans existing entries, and leaves `schedules` compatible
--      with the console's generic id-keyed Gateway (src/js/adminData.js)
--      and its demo overlay. A nullable `block_id` on `schedules` was
--      considered and deliberately left out.
--
--    • `schedule_configs.structure_type` is the hook for future schedule
--      structures. Only 'section' (one schedule shared by every student
--      in a section) is implemented. A per-student structure would widen
--      this CHECK and add a nullable owner column to `schedules`; nothing
--      here needs restructuring for that.
--
--    • `schedules.day_of_week` was capped at 1–5. Schools that teach on
--      Saturday exist, so the check widens to 1–7 and the active days of
--      a given year live in `schedule_configs.active_days`.
--
--  Already inlined in school_schema.sql for fresh per-school projects.
--  Apply this snippet by hand to a project that predates it — see
--  docs/ONBOARDING_RUNBOOK.md. Idempotent: safe to re-run.
-- ═══════════════════════════════════════════════════════════════

-- ── Per-year schedule configuration ──────────────────────────────
create table if not exists public.schedule_configs (
  id integer generated by default as identity primary key,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  structure_type character varying(20) not null default 'section'
    check (structure_type::text = any (array['section']::text[])),
  active_days smallint[] not null default '{1,2,3,4,5}'
    check (
      active_days <@ array[1,2,3,4,5,6,7]::smallint[]
      and cardinality(active_days) > 0
    ),
  created_at timestamp with time zone default now(),
  unique (school_year_id)
);

-- ── Reusable bell schedules (time-block templates) ───────────────
create table if not exists public.bell_schedules (
  id integer generated by default as identity primary key,
  name character varying(80) not null unique,
  created_at timestamp with time zone default now()
);

create table if not exists public.bell_schedule_blocks (
  id integer generated by default as identity primary key,
  bell_schedule_id integer not null references public.bell_schedules(id) on delete cascade,
  label character varying(80) not null,
  kind character varying(20) not null default 'class'
    check (kind::text = any (array['class','break']::text[])),
  block_order integer not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  check (start_time < end_time),
  unique (bell_schedule_id, block_order)
);

-- ── Widen the school week: Mon–Fri → any day ─────────────────────
-- NOTE: the constraint name below is the one Postgres generates for the
-- inline check in school_schema.sql. Verify it on the target project
-- before running (\d public.schedules) — a project whose schema was
-- applied out of band may carry a different name.
alter table public.schedules
  drop constraint if exists schedules_day_of_week_check;
alter table public.schedules
  add constraint schedules_day_of_week_check
  check (day_of_week >= 1 and day_of_week <= 7);

-- ── Row-level security ───────────────────────────────────────────
alter table public.schedule_configs enable row level security;
alter table public.bell_schedules enable row level security;
alter table public.bell_schedule_blocks enable row level security;

drop policy if exists "Admins have full access to schedule_configs"
  on public.schedule_configs;
create policy "Admins have full access to schedule_configs"
  on public.schedule_configs
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins have full access to bell_schedules"
  on public.bell_schedules;
create policy "Admins have full access to bell_schedules"
  on public.bell_schedules
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins have full access to bell_schedule_blocks"
  on public.bell_schedule_blocks;
create policy "Admins have full access to bell_schedule_blocks"
  on public.bell_schedule_blocks
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Signed-in users read the structure: the student and teacher portals
-- need the active days, and block labels caption the weekly grid.
drop policy if exists "Authenticated can read schedule_configs"
  on public.schedule_configs;
create policy "Authenticated can read schedule_configs"
  on public.schedule_configs
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can read bell_schedules"
  on public.bell_schedules;
create policy "Authenticated can read bell_schedules"
  on public.bell_schedules
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can read bell_schedule_blocks"
  on public.bell_schedule_blocks;
create policy "Authenticated can read bell_schedule_blocks"
  on public.bell_schedule_blocks
  for select using (auth.role() = 'authenticated');

-- ── Fixes a gap: teachers could not read schedules ───────────────
-- `schedules` only ever had an admin policy and a student policy scoped
-- to the student's own class, so on a real project the teacher console's
-- schedule view came back empty. Teaching staff need to read the
-- timetable of the classes they teach; this matches how every other
-- structure table (classes, subjects, rooms…) is already exposed.
drop policy if exists "Authenticated can read schedules" on public.schedules;
create policy "Authenticated can read schedules"
  on public.schedules
  for select using (auth.role() = 'authenticated');

-- NOTE: the shared demo project additionally carries the read-only lock every
-- other table there has (restrictive demo_deny_insert/update/delete for
-- anon + authenticated). Real school projects must NOT have those — admins
-- need to write. Applied to the demo project out of band, like the rest of
-- its schema.
