-- ═══════════════════════════════════════════════════════════════
--  school_schema.sql — baseline schema for a real (per-school) SMP project
--
--  Apply this to a fresh, empty Supabase project to onboard a school.
--  It mirrors the shared demo project's schema EXCEPT it omits the
--  demo read-only "demo_deny_*" restrictive policies — so admins can
--  actually write. Row-level security still applies: every table has an
--  is_admin() full-access policy plus the same student/teacher read
--  policies as the demo. Id columns use identity (functionally identical
--  to the demo's sequences).
--
--  Idempotent-ish: safe to run once on an empty project. See
--  docs/ONBOARDING_RUNBOOK.md for the full onboarding steps.
-- ═══════════════════════════════════════════════════════════════

-- ── Role enum ───────────────────────────────────────────────────
do $$ begin
  create type public.user_role_enum as enum ('student', 'teacher', 'admin');
exception when duplicate_object then null; end $$;

-- ═══════════════════════════════════════════════════════════════
--  Tables (created before the functions/policies that reference them)
-- ═══════════════════════════════════════════════════════════════
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role public.user_role_enum default 'student'::public.user_role_enum,
  created_at timestamp without time zone default now()
);

create table public.app_config (
  key text primary key,
  value text not null
);

create table public.school_years (
  id integer generated by default as identity primary key,
  name character varying(20) not null unique,
  start_date date not null,
  end_date date not null,
  is_active boolean default false,
  created_at timestamp with time zone default now()
);

create table public.grade_levels (
  id integer generated by default as identity primary key,
  name character varying(50) not null unique,
  numeric_level integer not null unique
);

create table public.rooms (
  id integer generated by default as identity primary key,
  name character varying(50) not null unique,
  capacity integer,
  type character varying(30) default 'classroom'::character varying
    check (type::text = any (array['classroom','lab','gym','library','auditorium','office']::text[]))
);

create table public.subjects (
  id integer generated by default as identity primary key,
  name character varying(100) not null unique,
  code character varying(10) unique,
  description text,
  color character varying(7)
);

create table public.teachers (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  email character varying(150) unique,
  phone character varying(20),
  address text,
  hire_date date,
  specialization character varying(100),
  status character varying(20) default 'active'::character varying
    check (status::text = any (array['active','inactive','on_leave']::text[])),
  created_at timestamp with time zone default now(),
  auth_user_id uuid unique references auth.users(id) on delete set null
);

create table public.staff (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  role character varying(50) not null,
  email character varying(150) unique,
  phone character varying(20),
  hire_date date,
  status character varying(20) default 'active'::character varying
    check (status::text = any (array['active','inactive']::text[])),
  created_at timestamp with time zone default now()
);

create table public.guardians (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  relationship character varying(50),
  phone character varying(20),
  alt_phone character varying(20),
  email character varying(150),
  address text,
  occupation character varying(100),
  created_at timestamp with time zone default now()
);

create table public.classes (
  id integer generated by default as identity primary key,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  grade_level_id integer not null references public.grade_levels(id),
  section character varying(10) not null,
  display_name character varying(20),
  homeroom_teacher_id integer references public.teachers(id) on delete set null,
  room_id integer references public.rooms(id) on delete set null,
  max_capacity integer default 30,
  unique (school_year_id, grade_level_id, section)
);

create table public.students (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  enrollment_number character varying(20) not null unique,
  date_of_birth date,
  gender character(1) check (gender = any (array['M'::bpchar,'F'::bpchar,'O'::bpchar])),
  class_id integer references public.classes(id) on delete set null,
  phone character varying(20),
  email character varying(150),
  address text,
  photo_url text,
  status character varying(20) default 'active'::character varying
    check (status::text = any (array['active','inactive','graduated','transferred','withdrawn']::text[])),
  enrollment_date date default CURRENT_DATE,
  created_at timestamp with time zone default now(),
  auth_user_id uuid references auth.users(id)
);

create table public.student_guardians (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  guardian_id integer not null references public.guardians(id) on delete cascade,
  is_primary boolean default false,
  unique (student_id, guardian_id)
);

create table public.grade_level_subjects (
  id integer generated by default as identity primary key,
  grade_level_id integer not null references public.grade_levels(id) on delete cascade,
  subject_id integer not null references public.subjects(id) on delete cascade,
  weekly_hours integer default 4,
  unique (grade_level_id, subject_id)
);

create table public.class_subject_teachers (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  subject_id integer not null references public.subjects(id) on delete cascade,
  teacher_id integer not null references public.teachers(id) on delete restrict,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  unique (class_id, subject_id, school_year_id)
);

create table public.grading_periods (
  id integer generated by default as identity primary key,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  name character varying(50) not null,
  start_date date not null,
  end_date date not null,
  weight numeric(5,2) default 33.33,
  period_order integer not null,
  unique (school_year_id, period_order)
);

create table public.schedules (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  subject_id integer not null references public.subjects(id) on delete cascade,
  teacher_id integer not null references public.teachers(id) on delete cascade,
  day_of_week smallint not null check (day_of_week >= 1 and day_of_week <= 5),
  start_time time without time zone not null,
  end_time time without time zone not null,
  room_id integer references public.rooms(id) on delete set null,
  unique (class_id, day_of_week, start_time)
);

create table public.attendance (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  class_id integer not null references public.classes(id) on delete cascade,
  date date not null,
  status character varying(20) not null
    check (status::text = any (array['present','absent','late','excused']::text[])),
  notes text,
  recorded_by integer references public.teachers(id) on delete set null,
  created_at timestamp with time zone default now(),
  unique (student_id, class_id, date),
  unique (student_id, date)
);

create table public.grade_categories (
  id integer generated by default as identity primary key,
  class_subject_teacher_id integer not null references public.class_subject_teachers(id) on delete cascade,
  name character varying not null,
  weight numeric not null default 0 check (weight >= 0),
  created_at timestamp with time zone default now(),
  unique (class_subject_teacher_id, name)
);

create table public.assignments (
  id integer generated by default as identity primary key,
  class_subject_teacher_id integer not null references public.class_subject_teachers(id) on delete cascade,
  grading_period_id integer not null references public.grading_periods(id) on delete restrict,
  name character varying(150) not null,
  due_date date,
  max_score numeric(6,2) not null default 100 check (max_score > 0),
  note text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  category_id integer references public.grade_categories(id) on delete set null
);

create table public.assignment_grades (
  id integer generated by default as identity primary key,
  assignment_id integer not null references public.assignments(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  score numeric(6,2) check (score >= 0),
  note text,
  graded_at timestamp with time zone default now(),
  created_at timestamp with time zone not null default now(),
  unique (assignment_id, student_id)
);

create table public.student_grades (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  class_subject_teacher_id integer not null references public.class_subject_teachers(id) on delete cascade,
  grading_period_id integer not null references public.grading_periods(id) on delete cascade,
  score numeric(5,2) check (score >= 0 and score <= 100),
  notes text,
  submitted_at timestamp with time zone default now(),
  unique (student_id, class_subject_teacher_id, grading_period_id)
);

create table public.discipline_records (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  date date not null default CURRENT_DATE,
  type character varying(50) not null,
  description text,
  severity character varying(20) default 'low'::character varying
    check (severity::text = any (array['low','medium','high']::text[])),
  reported_by_teacher integer references public.teachers(id) on delete set null,
  reported_by_staff integer references public.staff(id) on delete set null,
  resolved boolean default false,
  resolution text,
  created_at timestamp with time zone default now()
);

create table public.events (
  id integer generated by default as identity primary key,
  title character varying(200) not null,
  description text,
  start_date date not null,
  end_date date,
  type character varying(30) default 'general'::character varying
    check (type::text = any (array['holiday','exam_period','activity','parent_meeting','suspension','general']::text[])),
  affects_classes boolean default true,
  created_by integer references public.staff(id) on delete set null,
  created_at timestamp with time zone default now()
);

-- ═══════════════════════════════════════════════════════════════
--  Functions + auth→profiles trigger (after the tables they touch)
-- ═══════════════════════════════════════════════════════════════
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path to 'public'
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path to 'public'
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Harden the SECURITY DEFINER helpers: handle_new_user() only runs from the
-- trigger; is_admin() is evaluated by authenticated users inside RLS policies
-- (so it keeps EXECUTE for authenticated) but anon never needs it.
revoke execute on function public.handle_new_user() from anon, authenticated, public;
revoke execute on function public.is_admin() from anon;

-- ═══════════════════════════════════════════════════════════════
--  Row-level security: admin full access + student/teacher reads
--  (no demo read-only lock — admins can write on a real project)
-- ═══════════════════════════════════════════════════════════════
do $$
declare tbl text;
begin
  foreach tbl in array array[
    'profiles','app_config','school_years','grade_levels','rooms','subjects',
    'teachers','staff','guardians','classes','students','student_guardians',
    'grade_level_subjects','class_subject_teachers','grading_periods','schedules',
    'attendance','grade_categories','assignments','assignment_grades',
    'student_grades','discipline_records','events'
  ]
  loop
    execute format('alter table public.%I enable row level security;', tbl);
  end loop;

  -- Admins can do everything on every table.
  foreach tbl in array array[
    'profiles','app_config','school_years','grade_levels','rooms','subjects',
    'teachers','staff','guardians','classes','students','student_guardians',
    'grade_level_subjects','class_subject_teachers','grading_periods','schedules',
    'attendance','grade_categories','assignments','assignment_grades',
    'student_grades','discipline_records','events'
  ]
  loop
    execute format(
      'create policy "Admins have full access to %1$s" on public.%1$I '
      || 'for all to authenticated using (public.is_admin()) with check (public.is_admin());',
      tbl);
  end loop;

  -- Authenticated users can read reference/structure tables.
  foreach tbl in array array[
    'app_config','school_years','grade_levels','rooms','subjects','teachers',
    'classes','grade_level_subjects','class_subject_teachers','grading_periods','events'
  ]
  loop
    execute format(
      'create policy "Authenticated can read %1$s" on public.%1$I '
      || 'for select using (auth.role() = ''authenticated'');',
      tbl);
  end loop;
end $$;

-- Own-profile read/update.
create policy "Users can read their own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Students read their own linked rows.
create policy "Users can read their own student record" on public.students
  for select using (auth.uid() = auth_user_id);
create policy "Students read their attendance" on public.attendance
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their grades" on public.student_grades
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their discipline" on public.discipline_records
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their guardian links" on public.student_guardians
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their guardians" on public.guardians
  for select using (id in (
    select sg.guardian_id from public.student_guardians sg
    join public.students s on s.id = sg.student_id
    where s.auth_user_id = auth.uid()));
create policy "Students read their class schedule" on public.schedules
  for select using (class_id in (select class_id from public.students where auth_user_id = auth.uid()));
